# Generated by Django 3.2.3 on 2021-05-17 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('app', models.TextField(blank=True, null=True)),
                ('exports', models.IntegerField(default=0)),
                ('cover_img', models.TextField(default=True, null=True)),
                ('server_number', models.IntegerField(default=0)),
                ('port', models.IntegerField()),
                ('output_type', models.CharField(choices=[('application/json', '.json'), ('text/plain', '.txt'), ('text/csv', '.csv'), ('text/markdown', '.md'), ('image/bmp', '.bmp'), ('image/gif', '.gif'), ('image/vnd.microsoft.icon', '.ico'), ('image/jpeg', '.jpg'), ('image/jpeg', '.jpeg'), ('image/png', '.png'), ('image/svg+xml', '.svg'), ('image/tiff', '.tif'), ('image/tiff', '.tiff'), ('image/webp', '.webp'), ('application/pdf', '.pdf')], default='application/json', max_length=30, verbose_name='output_type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InputSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('variable_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(max_length=20)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_spec', to='apps.app')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
