# Generated by Django 3.2 on 2021-04-07 02:35

import apps.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=300)),
                ('app', models.FileField(upload_to=apps.functions.upload_to)),
                ('exports', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
