# Generated by Django 3.2 on 2021-04-07 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_app_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
