# Generated by Django 3.2.3 on 2021-05-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_app_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputspec',
            name='extra_type',
            field=models.CharField(blank=True, choices=[('SINGLE_CHOICE', 'Single Choice'), ('MULTIPLE_CHOICE', 'Multiple Choice')], max_length=30, null=True, verbose_name='extra_type'),
        ),
    ]
