# Generated by Django 3.2 on 2021-05-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_app_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='output_type',
            field=models.CharField(choices=[('STRING', 'String'), ('HTML', 'Html'), ('IMAGE', 'Image'), ('AUDIO', 'Audio'), ('VIDEO', 'Video'), ('FILE', 'File')], default='STRING', max_length=20, verbose_name='output_type'),
        ),
    ]
