# Generated by Django 3.2 on 2021-05-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_remove_app_static'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='has_file_input',
            field=models.BooleanField(default=False),
        ),
    ]
