# Generated by Django 3.2 on 2021-05-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_app_output_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='has_file_input',
        ),
        migrations.AlterField(
            model_name='inputspec',
            name='type',
            field=models.CharField(max_length=20),
        ),
    ]
