# Generated by Django 3.2 on 2021-05-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_app_has_file_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='cover_img',
            field=models.TextField(blank=True, null=True),
        ),
    ]
