# Generated by Django 3.2 on 2021-04-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_alter_app_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='static',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='app',
            name='app',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='app',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
