version: "3.3"

services:
  server:
    build:
      context: ./server
    ports:
      - "__PORT:5000"
  # nginx:
  #     image: nginx:latest
  #     ports:
  #         - "__PORT:__PORT"
  #     depends_on:
  #         - server
