version: "3.3"

services:
  server__ID:
    build:
      context: ./server
    ports:
      - "__PORT:5000"
    deploy:
      resources:
        limits:
          cpus: 0.50
          memory: 128M
  # nginx:
  #     image: nginx:latest
  #     ports:
  #         - "__PORT:__PORT"
  #     depends_on:
  #         - server
