version: "3.3"

services:
  server14:
    build:
      context: ./server
    ports:
      - "10000:5000"
    deploy:
      resources:
        limits:
          cpus: 0.50
          memory: 128M
  # nginx:
  #     image: nginx:latest
  #     ports:
  #         - "10000:10000"
  #     depends_on:
  #         - server
