# Generated by Django 3.2 on 2021-04-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_remove_app_static'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='imported',
            field=models.ManyToManyField(related_name='user', to='apps.App'),
        ),
    ]
