# Generated by Django 3.2.3 on 2021-05-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_login_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='login_method',
            field=models.CharField(choices=[('email', 'Email'), ('google', 'Google')], default='email', max_length=20, verbose_name='login_method'),
        ),
    ]
