# Generated by Django 3.2 on 2021-05-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='email',
            field=models.CharField(default='anonymous', max_length=50),
        ),
    ]
